### ISSUE TITLE
Exception errors occured while processing results from powershell

### ISSUE THREAD

**Issue by Rick-Jongbloed** [Tools4everBV/HelloID-Conn-Prov-Source-RAET-IAM-API#1]
Please remove the following two lines from the top of the scripts:

$Script:AuthenticationHeaders 
$Script:expirationTimeAccessToken

Leaving these in will generate four exception messages in the agent log:

`2020-09-18 12:45:54,570 [229] [4936d3d5-3a13-40ab-84b5-1a71fbf394ee] ERROR HelloID.Provisioning.Agent.WampServices.PowerShellService - Exception occurred while processing results from powershell: Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at HelloID.Provisioning.Agent.WampServices.PowerShellService.OutputCollectionOnDataAdded(Object sender, DataAddedEventArgs eventArgs) in D:\HelloID\Agent2\_work\21\s\agent\src\Main\WampServices\PowerShellService.cs:line 210
2020-09-18 12:45:54,570 [229] [4936d3d5-3a13-40ab-84b5-1a71fbf394ee] ERROR HelloID.Provisioning.Agent.WampServices.PowerShellService - Exception occurred while processing results from powershell: Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at HelloID.Provisioning.Agent.WampServices.PowerShellService.OutputCollectionOnDataAdded(Object sender, DataAddedEventArgs eventArgs) in D:\HelloID\Agent2\_work\21\s\agent\src\Main\WampServices\PowerShellService.cs:line 210
2020-09-18 12:45:54,570 [229] [1e5abb1b-3078-4496-a0ce-f52c3e4d2cf8] ERROR HelloID.Provisioning.Agent.WampServices.PowerShellService - Exception occurred while processing results from powershell: Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at HelloID.Provisioning.Agent.WampServices.PowerShellService.OutputCollectionOnDataAdded(Object sender, DataAddedEventArgs eventArgs) in D:\HelloID\Agent2\_work\21\s\agent\src\Main\WampServices\PowerShellService.cs:line 210
2020-09-18 12:45:54,570 [229] [1e5abb1b-3078-4496-a0ce-f52c3e4d2cf8] ERROR HelloID.Provisioning.Agent.WampServices.PowerShellService - Exception occurred while processing results from powershell: Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at HelloID.Provisioning.Agent.WampServices.PowerShellService.OutputCollectionOnDataAdded(Object sender, DataAddedEventArgs eventArgs) in D:\HelloID\Agent2\_work\21\s\agent\src\Main\WampServices\PowerShellService.cs:line 210`

**Comment by Rick-Jongbloed** [comment]
solved by https://github.com/Tools4everBV/HelloID-Conn-Prov-Source-RAET-IAM-API/commit/1f728eea0216f1567fe28a314f1aa2a0a0ed4808
